### ISSUE TITLE
Infografía Realidad Aumentada_Antonio González Hernández

### ISSUE THREAD

**Issue by Anthony4523** [SistemasTecTlaxiaco/infografia-Anthony4523#1]
![Realidad Aumentada](https://user-images.githubusercontent.com/73609728/153735406-e31528ab-3e20-4595-837c-88328a2ffa56.png)

**Comment by garaudy12** [comment]
Excelente trabajo cumple con todos los aspectos de la rúbrica 20/20.

**Comment by josealfredo79** [comment]
Bien bien,,,revisado
