### ISSUE TITLE
Infografía "Ingeniería de Requisitos"

### ISSUE THREAD

**Issue by Anthony4523** [SistemasTecTlaxiaco/infografia-Anthony4523#2]
![Ingeniería de Requisitos](https://user-images.githubusercontent.com/73609728/110197262-04cc3380-7e10-11eb-9fcb-2af2aeaf6aed.png)

**Comment by Brendalp** [comment]
Calificación= 20

**Comment by josealfredo79** [comment]
Bien hecho.y revisado.
